### ISSUE TITLE
Extend the duration period to indefinitely 

### ISSUE THREAD

**Issue by AvrumFeldman** [exeldro/obs-freeze-filter#1]
Hi,

Would it be possible to extend the ability to set the duration for indefinitely? currently the max seems to be `99999ms`.

Thanks

**Comment by exeldro** [comment]
It is possible to set a higher limit, but most computers don't have indefinite amounts of memory. You can set a higher value in the settings file if you want to use it without changes to the plugin.

**Comment by AvrumFeldman** [comment]
Didn't realize it fills up the memory.

Can you please point me to the direction of the settings file? I can't seem to find it.

**Comment by exeldro** [comment]
Sorry I was thinking about an other plugin. Longer times don't use memory. If you set the duration to 0 it should always stay frozen.

**Comment by AvrumFeldman** [comment]
Got it. Thanks so much. Amazing plugin.
