### ISSUE TITLE
When used in studio mode, program view stays frozen

### ISSUE THREAD

**Issue by AvrumFeldman** [exeldro/obs-freeze-filter#2]
Hi,

Using OBS 25.0.8, when using this plugin in studio mode, the program section (where the live stream is actually shown) gets frozen on one frame and doesn't move forward. Disabling Studio mode solves the issue, but it's a pretty hard workaround as that prevents us from playing with scenes while streaming.

**Comment by AvrumFeldman** [comment]
Hi,

I understand this might not be a big priority for you. I have a very unique setup that is fully dependent on this filter. Is there any way we can get a fix for this?

**Comment by exeldro** [comment]
It only happens when you have duplication mode on in studio mode on sources that allow to be duplicated.
I will make a fix later this week.

**Comment by AvrumFeldman** [comment]
Thanks for looking into it. ~Looking forward for the fix.~ Wow didn't realize you already gave out a fix. You are amazing! Thanks tonz.

~Anywhere we can donate?~ Found.

**Comment by AvrumFocus** [comment]
Thanks so much for the fix.

**Comment by exeldro** [comment]
It should be fixed in the today released version 0.2.0
Thank you for the donation.
